$(document).ready(function(){
    $("#work1").mouseover(function(){
      $("#hover1").show();
    }).mouseout(function(){
      $("#hover1").hide();
    });
});
$(document).ready(function(){
    $("#work2").mouseover(function(){
      $("#hover2").show();
    }).mouseout(function(){
      $("#hover2").hide();
    });
});
$(document).ready(function(){
    $("#work3").mouseover(function(){
      $("#hover3").show();
    }).mouseout(function(){
      $("#hover3").hide();
    });
});
$(document).ready(function(){
    $("#work4").mouseover(function(){
      $("#hover4").show();
    }).mouseout(function(){
      $("#hover4").hide();
    });
});