$(document).ready(function(){
    $("#design-image").click(function(){
      $("#design-image").slideDown('1500').hide('1000');
      $("#design").show('1500');
    });
    $("#design").click(function(){
      $("#design").slideUp('1500');
      $("#design-image").slideDown('1500');
    });
  });
  $(document).ready(function(){
    $("#development-image").click(function(){
      $("#development-image").slideDown('1500').hide('1000');
      $("#development").show('1500');
    });
    $("#development").click(function(){
      $("#development").slideUp('1500');
      $("#development-image").slideDown('1500');
    });
  });
  $(document).ready(function(){
    $("#product-image").click(function(){
      $("#product-image").slideDown('1500').hide('1000');
      $("#pm").show('1500');
    });
    $("#pm").click(function(){
      $("#pm").slideUp('1500');
      $("#product-image").slideDown('1500');
    });
  });
$(document).ready(function(){
    $("#work1").mouseover(function(){
      $("#hover1").show();
    }).mouseout(function(){
      $("#hover1").hide();
    });
});
$(document).ready(function(){
    $("#work2").mouseover(function(){
      $("#hover2").show();
    }).mouseout(function(){
      $("#hover2").hide();
    });
});
$(document).ready(function(){
    $("#work3").mouseover(function(){
      $("#hover3").show();
    }).mouseout(function(){
      $("#hover3").hide();
    });
});
$(document).ready(function(){
    $("#work4").mouseover(function(){
      $("#hover4").show();
    }).mouseout(function(){
      $("#hover4").hide();
    });
});
$(document).ready(function(){
    $("#work5").mouseover(function(){
      $("#hover5").show();
    }).mouseout(function(){
      $("#hover5").hide();
    });
});
$(document).ready(function(){
    $("#work6").mouseover(function(){
      $("#hover6").show();
    }).mouseout(function(){
      $("#hover6").hide();
    });
});
$(document).ready(function(){
    $("#work7").mouseover(function(){
      $("#hover7").show();
    }).mouseout(function(){
      $("#hover7").hide();
    });
});
$(document).ready(function(){
    $("#work8").mouseover(function(){
      $("#hover8").show();
    }).mouseout(function(){
      $("#hover8").hide();
    });
});